/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UI.Operator;

import Business.AeroplaneCatalogue;
import Business.FleetCatalogue;
import Business.Flight;
import Business.Operator;
import java.awt.CardLayout;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author mahajan
 */
public class ViewSchedule extends javax.swing.JPanel {

    JPanel userProcessContainer;
    FleetCatalogue fc;
    AeroplaneCatalogue airpC;
    int option;
    
    public ViewSchedule(JPanel userProcessContainer, FleetCatalogue fc) {
        initComponents();
        this.userProcessContainer=userProcessContainer;
        this.fc=fc;
        displayTable();
        option=11;
    }

    public ViewSchedule(JPanel userProcessContainer, FleetCatalogue fc, AeroplaneCatalogue airpc) {
        initComponents();
        this.userProcessContainer=userProcessContainer;
        this.fc=fc;
        this.airpC=airpc;
        displayTable();
        option=22;
    }
    
    
    private void displayTable()
    {
        DefaultTableModel dtm = (DefaultTableModel)tblResult.getModel();
        dtm.setRowCount(0);
        for(Flight ff:fc.getFleetCat())
        {
            Object[] ob= new Object[3];
            ob[0]=ff;
            ob[1]=ff.getFromLoc();
            ob[2]=ff.getToLoc();
            dtm.addRow(ob);
            
        }
    }
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tblResult = new javax.swing.JTable();
        btnViewFlight = new javax.swing.JButton();
        lblResult = new javax.swing.JLabel();
        btnBack2 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();

        tblResult.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "From", "To"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblResult.getTableHeader().setReorderingAllowed(false);
        jScrollPane1.setViewportView(tblResult);
        if (tblResult.getColumnModel().getColumnCount() > 0) {
            tblResult.getColumnModel().getColumn(0).setResizable(false);
            tblResult.getColumnModel().getColumn(1).setResizable(false);
            tblResult.getColumnModel().getColumn(2).setResizable(false);
        }

        btnViewFlight.setText("View Flight");
        btnViewFlight.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnViewFlightActionPerformed(evt);
            }
        });

        lblResult.setFont(new java.awt.Font("Lucida Grande", 1, 18)); // NOI18N
        lblResult.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblResult.setText("Schedule");

        btnBack2.setText("<<Back");
        btnBack2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBack2ActionPerformed(evt);
            }
        });

        jButton1.setText("Cancel Flight");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(174, 174, 174)
                .addComponent(lblResult, javax.swing.GroupLayout.DEFAULT_SIZE, 357, Short.MAX_VALUE)
                .addGap(174, 174, 174))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnViewFlight))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(33, 33, 33)
                        .addComponent(jScrollPane1)))
                .addGap(35, 35, 35))
            .addGroup(layout.createSequentialGroup()
                .addComponent(btnBack2)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblResult, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 401, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnViewFlight)
                    .addComponent(jButton1))
                .addGap(8, 8, 8)
                .addComponent(btnBack2))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnBack2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBack2ActionPerformed
        
        userProcessContainer.remove(this);
        CardLayout layout= (CardLayout) userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
        
        
    }//GEN-LAST:event_btnBack2ActionPerformed

    private void btnViewFlightActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnViewFlightActionPerformed
        
        int getSelected= tblResult.getSelectedRow();
        if(getSelected>=0)
        {
            Flight arer=new Flight();
            arer=(Flight)tblResult.getValueAt(getSelected, 0);
            if(option==22)
            {
                ViewFlight vfl = new ViewFlight(userProcessContainer, arer, airpC);
                userProcessContainer.add("AddAirplane",vfl);
                CardLayout layout = (CardLayout)userProcessContainer.getLayout();
                layout.next(userProcessContainer);
            }
            if(option==11)
            {
                ViewFlight vfl = new ViewFlight(userProcessContainer, arer);
                userProcessContainer.add("AddAirplane",vfl);
                CardLayout layout = (CardLayout)userProcessContainer.getLayout();
                layout.next(userProcessContainer);
            }
        }
        else
            JOptionPane.showMessageDialog(null, "Select Row", "Error", 0);
        
        
        
        
    }//GEN-LAST:event_btnViewFlightActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        int getSelected= tblResult.getSelectedRow();
        if(getSelected>=0)
        {
            Flight arer=new Flight();
            arer=(Flight)tblResult.getValueAt(getSelected, 0);
            fc.removeAeroplane(arer);
            displayTable();
        }
        else
            JOptionPane.showMessageDialog(null, "Select Row", "Error", 0);
        
    }//GEN-LAST:event_jButton1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack2;
    private javax.swing.JButton btnViewFlight;
    private javax.swing.JButton jButton1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblResult;
    private javax.swing.JTable tblResult;
    // End of variables declaration//GEN-END:variables
}
