/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interface;

import BusinessLogic.PersonInfo;
import java.io.File;
import javax.swing.JFileChooser;

import javax.swing.JOptionPane;


/**
 *
 * @author mahajan
 */
public class CreateProfile extends javax.swing.JPanel {

    /**
     * Creates new form createProfile
     */
    
    private PersonInfo personInfo;
    
    public CreateProfile(PersonInfo personInfo) {
        initComponents();
        this.personInfo = personInfo;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        CreateProfileLBL = new javax.swing.JLabel();
        usrNameLBL = new javax.swing.JLabel();
        usrName = new javax.swing.JTextField();
        geogDataLBL = new javax.swing.JLabel();
        geogData = new javax.swing.JTextField();
        dOBLBL = new javax.swing.JLabel();
        dOB = new javax.swing.JTextField();
        telNOLBL = new javax.swing.JLabel();
        telNO = new javax.swing.JTextField();
        eMailLBL = new javax.swing.JLabel();
        eMail = new javax.swing.JTextField();
        ssnLBL = new javax.swing.JLabel();
        ssn = new javax.swing.JTextField();
        bankAccNoLBL = new javax.swing.JLabel();
        bankAccNo = new javax.swing.JTextField();
        vehLicNoLBL = new javax.swing.JLabel();
        vehLicNo = new javax.swing.JTextField();
        deviceIDLBL = new javax.swing.JLabel();
        deviceID = new javax.swing.JTextField();
        linkedINLBL = new javax.swing.JLabel();
        linkedIN = new javax.swing.JTextField();
        uniqueIDLBL = new javax.swing.JLabel();
        uniqueID = new javax.swing.JTextField();
        createButton = new javax.swing.JButton();
        chooseImgBtn = new javax.swing.JButton();
        chooseImgPath = new javax.swing.JTextField();

        jLabel1.setText("Choose Image");

        CreateProfileLBL.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        CreateProfileLBL.setText("Create Your Profile");

        usrNameLBL.setText("Name");

        geogDataLBL.setText("Address");

        dOBLBL.setText("DOB");

        telNOLBL.setText("Phone");

        eMailLBL.setText("Email");

        eMail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                eMailActionPerformed(evt);
            }
        });

        ssnLBL.setText("SSN");

        bankAccNoLBL.setText("Bank Account Number");

        vehLicNoLBL.setText("Vehicle Number ");

        deviceIDLBL.setText("Device ID");

        linkedINLBL.setText("LinkedIN");

        uniqueIDLBL.setText("Unique ID");

        createButton.setText("Create");
        createButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                createButtonActionPerformed(evt);
            }
        });

        chooseImgBtn.setText(" Image");
        chooseImgBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chooseImgBtnActionPerformed(evt);
            }
        });

        chooseImgPath.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chooseImgPathActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(geogDataLBL)
                            .addComponent(dOBLBL)
                            .addComponent(usrNameLBL)
                            .addComponent(telNOLBL)
                            .addComponent(eMailLBL)
                            .addComponent(ssnLBL))
                        .addGap(56, 56, 56)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(ssn, javax.swing.GroupLayout.DEFAULT_SIZE, 126, Short.MAX_VALUE)
                            .addComponent(eMail, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(telNO, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(usrName, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(dOB, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(geogData, javax.swing.GroupLayout.Alignment.LEADING))
                        .addGap(32, 32, 32)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(bankAccNoLBL)
                            .addComponent(vehLicNoLBL)
                            .addComponent(deviceIDLBL)
                            .addComponent(linkedINLBL)
                            .addComponent(uniqueIDLBL))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(bankAccNo)
                            .addComponent(vehLicNo)
                            .addComponent(deviceID)
                            .addComponent(linkedIN)
                            .addComponent(uniqueID)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(169, 169, 169)
                                .addComponent(CreateProfileLBL, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(chooseImgBtn)
                                .addGap(27, 27, 27)
                                .addComponent(chooseImgPath, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 174, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(createButton)
                .addGap(218, 218, 218))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(CreateProfileLBL)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(usrName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(usrNameLBL)
                    .addComponent(bankAccNoLBL)
                    .addComponent(bankAccNo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(geogDataLBL)
                    .addComponent(geogData, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(vehLicNo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(vehLicNoLBL))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(dOB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(dOBLBL)
                    .addComponent(deviceIDLBL)
                    .addComponent(deviceID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(telNO, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(telNOLBL)
                    .addComponent(linkedINLBL)
                    .addComponent(linkedIN, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(eMail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(eMailLBL)
                    .addComponent(uniqueIDLBL)
                    .addComponent(uniqueID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(11, 11, 11)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ssn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ssnLBL))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(chooseImgPath, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(chooseImgBtn))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 68, Short.MAX_VALUE)
                .addComponent(createButton)
                .addGap(17, 17, 17))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void eMailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_eMailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_eMailActionPerformed

    private void createButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_createButtonActionPerformed
        // TODO add your handling code here:
        personInfo.setUsrName(usrName.getText());
        personInfo.setGeogData(geogData.getText());
        personInfo.setdOB(dOB.getText());
        personInfo.setTelNo(telNO.getText());
        personInfo.seteMail(eMail.getText());
        personInfo.setSsn(ssn.getText());
        personInfo.setBankAccNo(bankAccNo.getText());
        personInfo.setVehLicNo(vehLicNo.getText());
        personInfo.setDeviceID(deviceID.getText());
        personInfo.setLinkedIN(linkedIN.getText());
        personInfo.setUniqueID(uniqueID.getText());
        personInfo.setImagePath(chooseImgPath.getText());
        
        String saveConfirm= "Data Stored Successfully";
        
        JOptionPane.showMessageDialog(null, saveConfirm);
        
        
        
    }//GEN-LAST:event_createButtonActionPerformed

    private void chooseImgPathActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chooseImgPathActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_chooseImgPathActionPerformed

    private void chooseImgBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chooseImgBtnActionPerformed
        // TODO add your handling code here:
        JFileChooser openImage = new JFileChooser();
        openImage.showOpenDialog(null);
        File image= openImage.getSelectedFile();
        String imgPath= image.getAbsolutePath();
        chooseImgPath.setText(imgPath);
        
        
        
        
    }//GEN-LAST:event_chooseImgBtnActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel CreateProfileLBL;
    private javax.swing.JTextField bankAccNo;
    private javax.swing.JLabel bankAccNoLBL;
    private javax.swing.JButton chooseImgBtn;
    private javax.swing.JTextField chooseImgPath;
    private javax.swing.JButton createButton;
    private javax.swing.JTextField dOB;
    private javax.swing.JLabel dOBLBL;
    private javax.swing.JTextField deviceID;
    private javax.swing.JLabel deviceIDLBL;
    private javax.swing.JTextField eMail;
    private javax.swing.JLabel eMailLBL;
    private javax.swing.JTextField geogData;
    private javax.swing.JLabel geogDataLBL;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JTextField linkedIN;
    private javax.swing.JLabel linkedINLBL;
    private javax.swing.JTextField ssn;
    private javax.swing.JLabel ssnLBL;
    private javax.swing.JTextField telNO;
    private javax.swing.JLabel telNOLBL;
    private javax.swing.JTextField uniqueID;
    private javax.swing.JLabel uniqueIDLBL;
    private javax.swing.JTextField usrName;
    private javax.swing.JLabel usrNameLBL;
    private javax.swing.JTextField vehLicNo;
    private javax.swing.JLabel vehLicNoLBL;
    // End of variables declaration//GEN-END:variables
}
