/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interface;

import BusinessLogic.PersonInfo;
import java.awt.Image;
import java.awt.image.BufferedImage;
import java.io.File;
import java.io.IOException;
import javax.imageio.ImageIO;
import javax.swing.ImageIcon;

/**
 *
 * @author mahajan
 */
public class ViewProfile extends javax.swing.JPanel {

    /**
     * Creates new form ViewProfile
     */
    private PersonInfo personInfo;
    public ViewProfile(PersonInfo personInfo) {
        initComponents();
        displayPersonInfo(personInfo);
    }
    
    
    
    private void displayPersonInfo(PersonInfo personInfo)
    {
        
        usrName.setText(personInfo.getUsrName());
        geogData.setText(personInfo.getGeogData());
        dOB.setText(personInfo.getdOB());
        telNO.setText(personInfo.getTelNo());
        eMail.setText(personInfo.geteMail());
        ssn.setText(personInfo.getSsn());
        bankAccNo.setText(personInfo.getBankAccNo());
        vehLicNo.setText(personInfo.getVehLicNo());
        deviceID.setText(personInfo.getDeviceID());
        linkedIN.setText(personInfo.getLinkedIN());
        uniqueID.setText(personInfo.getUniqueID());
        
        //ImageIcon perImg= new ImageIcon(personInfo.getImagePath());
        //personImage.setIcon(perImg);
//            Image pic = perImg.getImage();
//            personIMG = new JPanel() {
//            @Override
//            protected void paintComponent(Graphics g) {
//            super.paintComponent(g);
//            g.drawImage(pic, 0, 0, getWidth(), getHeight());
//            };
            
            BufferedImage img = null;
            try 
            {
                img = ImageIO.read(new File(personInfo.getImagePath()));
            } 
            catch (IOException e) 
            {
                e.printStackTrace();
            }
            Image pic = img.getScaledInstance(145, 171 ,Image.SCALE_SMOOTH);
            ImageIcon perImg= new ImageIcon(pic);
            personImage.setIcon(perImg);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        usrName = new javax.swing.JTextField();
        CreateProfileLBL = new javax.swing.JLabel();
        bankAccNoLBL = new javax.swing.JLabel();
        bankAccNo = new javax.swing.JTextField();
        usrNameLBL = new javax.swing.JLabel();
        geogDataLBL = new javax.swing.JLabel();
        dOBLBL = new javax.swing.JLabel();
        telNOLBL = new javax.swing.JLabel();
        eMailLBL = new javax.swing.JLabel();
        ssnLBL = new javax.swing.JLabel();
        ssn = new javax.swing.JTextField();
        eMail = new javax.swing.JTextField();
        telNO = new javax.swing.JTextField();
        dOB = new javax.swing.JTextField();
        geogData = new javax.swing.JTextField();
        vehLicNo = new javax.swing.JTextField();
        vehLicNoLBL = new javax.swing.JLabel();
        deviceIDLBL = new javax.swing.JLabel();
        linkedINLBL = new javax.swing.JLabel();
        uniqueIDLBL = new javax.swing.JLabel();
        uniqueID = new javax.swing.JTextField();
        linkedIN = new javax.swing.JTextField();
        deviceID = new javax.swing.JTextField();
        personImage = new javax.swing.JLabel();

        CreateProfileLBL.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        CreateProfileLBL.setText("Your Profile");

        bankAccNoLBL.setText("Bank Account Number");

        usrNameLBL.setText("Name");

        geogDataLBL.setText("Address");

        dOBLBL.setText("DOB");

        telNOLBL.setText("Phone");

        eMailLBL.setText("Email");

        ssnLBL.setText("SSN");

        eMail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                eMailActionPerformed(evt);
            }
        });

        vehLicNoLBL.setText("Vehicle Number ");

        deviceIDLBL.setText("Device ID");

        linkedINLBL.setText("LinkedIN");

        uniqueIDLBL.setText("Unique ID");

        uniqueID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                uniqueIDActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(CreateProfileLBL, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(geogDataLBL)
                            .addComponent(dOBLBL)
                            .addComponent(usrNameLBL)
                            .addComponent(telNOLBL)
                            .addComponent(eMailLBL)
                            .addComponent(ssnLBL))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(ssn, javax.swing.GroupLayout.DEFAULT_SIZE, 126, Short.MAX_VALUE)
                            .addComponent(eMail, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(telNO, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(usrName, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(dOB, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(geogData, javax.swing.GroupLayout.Alignment.LEADING))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(bankAccNoLBL)
                            .addComponent(vehLicNoLBL)
                            .addComponent(deviceIDLBL)
                            .addComponent(linkedINLBL)
                            .addComponent(uniqueIDLBL))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(bankAccNo, javax.swing.GroupLayout.DEFAULT_SIZE, 145, Short.MAX_VALUE)
                    .addComponent(vehLicNo)
                    .addComponent(deviceID)
                    .addComponent(linkedIN)
                    .addComponent(uniqueID)
                    .addComponent(personImage, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(CreateProfileLBL, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(usrName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(usrNameLBL)
                    .addComponent(bankAccNoLBL)
                    .addComponent(bankAccNo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(geogDataLBL)
                    .addComponent(geogData, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(vehLicNo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(vehLicNoLBL))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(dOB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(dOBLBL)
                    .addComponent(deviceIDLBL)
                    .addComponent(deviceID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(telNO, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(telNOLBL)
                    .addComponent(linkedINLBL)
                    .addComponent(linkedIN, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(eMail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(eMailLBL)
                    .addComponent(uniqueIDLBL)
                    .addComponent(uniqueID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(11, 11, 11)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(ssn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(ssnLBL))
                        .addGap(0, 145, Short.MAX_VALUE))
                    .addComponent(personImage, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void eMailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_eMailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_eMailActionPerformed

    private void uniqueIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_uniqueIDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_uniqueIDActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel CreateProfileLBL;
    private javax.swing.JTextField bankAccNo;
    private javax.swing.JLabel bankAccNoLBL;
    private javax.swing.JTextField dOB;
    private javax.swing.JLabel dOBLBL;
    private javax.swing.JTextField deviceID;
    private javax.swing.JLabel deviceIDLBL;
    private javax.swing.JTextField eMail;
    private javax.swing.JLabel eMailLBL;
    private javax.swing.JTextField geogData;
    private javax.swing.JLabel geogDataLBL;
    private javax.swing.JTextField linkedIN;
    private javax.swing.JLabel linkedINLBL;
    private javax.swing.JLabel personImage;
    private javax.swing.JTextField ssn;
    private javax.swing.JLabel ssnLBL;
    private javax.swing.JTextField telNO;
    private javax.swing.JLabel telNOLBL;
    private javax.swing.JTextField uniqueID;
    private javax.swing.JLabel uniqueIDLBL;
    private javax.swing.JTextField usrName;
    private javax.swing.JLabel usrNameLBL;
    private javax.swing.JTextField vehLicNo;
    private javax.swing.JLabel vehLicNoLBL;
    // End of variables declaration//GEN-END:variables
}
