/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interface.Customer;

import Business.Customer.CartProduct;
import Business.Customer.Customer;
import Business.Product;
import Business.Retailer.Retailer;
import Business.Retailer.RetailerCatalogue;
import Business.Validation.Validate;
import java.awt.CardLayout;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author mahajan
 */
public class BuyProduct extends javax.swing.JPanel {

    /**
     * Creates new form SearchProduct
     */
    private JPanel userProcessContainer;
    private Customer customer;
    private RetailerCatalogue zipRetailers;
    private RetailerCatalogue backup;

    BuyProduct(JPanel userProcessContainer, Customer cust, RetailerCatalogue retCal) {

        initComponents();
        getRetailers(retCal, cust.getZipCode());
        this.userProcessContainer = userProcessContainer;
        this.customer = cust;
        if (zipRetailers != null) {
            populateTable();
        }
        displayRetailers();
        this.backup = zipRetailers;

    }

    private void populateTable() {
        DefaultTableModel dtm = (DefaultTableModel) tblProd.getModel();
        dtm.setRowCount(0);

        ArrayList<Object[]> res;

        res = zipRetailers.getAllProducts();

        {
            for (Object[] ob : res) {
                dtm.addRow(ob);

            }
        }

    }

    private void getRetailers(RetailerCatalogue retCal, String zipCode) {
        ArrayList<Retailer> result = retCal.searchByZip(zipCode);
        if (result != null) {
            zipRetailers = new RetailerCatalogue(result);
        } else {
            JOptionPane.showMessageDialog(null, "No Retailers in Nearby Areas");
            getBack();
        }
    }

    private void getBack() {
        userProcessContainer.remove(this);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblHeader = new javax.swing.JLabel();
        btnBack = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblProd = new javax.swing.JTable();
        btnAddToCart = new javax.swing.JButton();
        lblProd = new javax.swing.JLabel();
        lblProdText = new javax.swing.JLabel();
        lblCost = new javax.swing.JLabel();
        lblCostText = new javax.swing.JLabel();
        lblQuantity = new javax.swing.JLabel();
        lblQuantityText = new javax.swing.JTextField();
        boxSelect = new javax.swing.JComboBox();
        lblCustomer = new javax.swing.JLabel();
        btnReset = new javax.swing.JButton();

        lblHeader.setFont(new java.awt.Font("Lucida Grande", 1, 18)); // NOI18N
        lblHeader.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblHeader.setText("Buy Product");

        btnBack.setText("<<Back");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });

        tblProd.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Retailer", "Product ID", "Name", "Cost", "Available Quantity"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblProd.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblProdMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblProd);
        if (tblProd.getColumnModel().getColumnCount() > 0) {
            tblProd.getColumnModel().getColumn(0).setResizable(false);
            tblProd.getColumnModel().getColumn(1).setResizable(false);
            tblProd.getColumnModel().getColumn(2).setResizable(false);
            tblProd.getColumnModel().getColumn(3).setResizable(false);
            tblProd.getColumnModel().getColumn(4).setResizable(false);
        }

        btnAddToCart.setText("Add to Cart");
        btnAddToCart.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddToCartActionPerformed(evt);
            }
        });

        lblProd.setText("Product:");

        lblCost.setText("Cost");

        lblQuantity.setText("Quantity:");

        boxSelect.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        boxSelect.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                boxSelectMouseClicked(evt);
            }
        });
        boxSelect.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boxSelectActionPerformed(evt);
            }
        });

        lblCustomer.setText("Retailer:");

        btnReset.setText("Reset Filters");
        btnReset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnResetActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(310, 310, 310)
                .addComponent(lblHeader, javax.swing.GroupLayout.DEFAULT_SIZE, 270, Short.MAX_VALUE)
                .addGap(320, 320, 320))
            .addGroup(layout.createSequentialGroup()
                .addComponent(btnBack)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblProd, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblCost))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lblProdText, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblCostText, javax.swing.GroupLayout.DEFAULT_SIZE, 165, Short.MAX_VALUE))
                .addGap(86, 86, 86)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblCustomer)
                    .addComponent(lblQuantity, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblQuantityText, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnAddToCart))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnReset)
                            .addComponent(boxSelect, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblHeader, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 265, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblProdText, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btnAddToCart)
                        .addComponent(lblProd, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lblQuantity)
                        .addComponent(lblQuantityText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(lblCost)
                        .addComponent(lblCostText, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(boxSelect, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblCustomer, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnReset)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 114, Short.MAX_VALUE)
                .addComponent(btnBack))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        userProcessContainer.remove(this);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
    }//GEN-LAST:event_btnBackActionPerformed

    private void tblProdMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblProdMouseClicked

        int getSelected = tblProd.getSelectedRow();
        Product arer;
        if (getSelected >= 0) {
            arer = (Product) tblProd.getValueAt(getSelected, 2);
            lblProdText.setText(arer.getProductName());
            lblCostText.setText(String.valueOf(arer.getPrice()));

        }


    }//GEN-LAST:event_tblProdMouseClicked

    private void btnAddToCartActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddToCartActionPerformed

        int getSelected = tblProd.getSelectedRow();
        Product arer;

        if (Validate.integerCheck(lblQuantityText.getText(), "Quantity")) {
            int quantity = Integer.parseInt(lblQuantityText.getText());

            if (getSelected >= 0) {
                arer = (Product) tblProd.getValueAt(getSelected, 2);
                if (quantity < arer.getAvailableUnits()) {
                    CartProduct cp = new CartProduct(arer, quantity);
                    customer.getCartCatalogue().addCartCat(cp);
                    arer.setAvailableUnits(arer.getAvailableUnits() - Integer.parseInt(lblQuantityText.getText()));

                    JOptionPane.showMessageDialog(null, "Product Added Successfully");
                    populateTable();
                } else {
                    JOptionPane.showMessageDialog(null, "Not Enough Units");
                }
            } else {
                JOptionPane.showMessageDialog(null, "Select Row", "Error", 0);
            }

        }

    }//GEN-LAST:event_btnAddToCartActionPerformed

    private void displayRetailers() {

        boxSelect.removeAllItems();

        for (Retailer ret : zipRetailers.getRetailerCatalogue()) {
            boxSelect.addItem(ret);
        }

    }


    private void boxSelectActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boxSelectActionPerformed
           
    }//GEN-LAST:event_boxSelectActionPerformed

    private void boxSelectMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_boxSelectMouseClicked

        Retailer rm = (Retailer) boxSelect.getSelectedItem();

        if (rm != null) {
            
            ArrayList<Retailer> result = backup.searchByRetailer(rm);
            if (result != null) {
                zipRetailers = new RetailerCatalogue(result);
            }
            populateTable();

        }


    }//GEN-LAST:event_boxSelectMouseClicked

    private void btnResetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnResetActionPerformed

        zipRetailers = backup;
        populateTable();


    }//GEN-LAST:event_btnResetActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox boxSelect;
    private javax.swing.JButton btnAddToCart;
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnReset;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblCost;
    private javax.swing.JLabel lblCostText;
    private javax.swing.JLabel lblCustomer;
    private javax.swing.JLabel lblHeader;
    private javax.swing.JLabel lblProd;
    private javax.swing.JLabel lblProdText;
    private javax.swing.JLabel lblQuantity;
    private javax.swing.JTextField lblQuantityText;
    private javax.swing.JTable tblProd;
    // End of variables declaration//GEN-END:variables
}
