/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interface.Customer;

import Business.Admin;
import Business.Customer.CartCatalogue;
import Business.Customer.CartProduct;
import Business.Customer.Customer;
import Business.Product;
import Business.Retailer.RetailerCatalogue;
import Business.Validation.Validate;
import java.awt.CardLayout;
import java.awt.Component;
import java.util.ArrayList;
import java.util.Calendar;
import javax.swing.JOptionPane;
import javax.swing.JPanel;


/**
 *
 * @author mahajan
 */
public class CheckoutPanel extends javax.swing.JPanel {

    /**
     * Creates new form CheckoutPanel
     */
    JPanel userProcessContainer;
    Customer cust;
    private RetailerCatalogue retCal;
    public CheckoutPanel(JPanel userProcessContainer, Customer cust, RetailerCatalogue retCal) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.cust = cust;
        this.retCal = retCal;
        costCalculate();
    }
    private void costCalculate()
    {
        Double costc= 0.0;
        ArrayList<Object[]> res;
        res= cust.getCart();
        if(res!=null)
        {
            for(Object[] ob:res)
            {
                Product p=(Product)ob[0];
                CartProduct cpp=(CartProduct)ob[1];
                int no=(int)cpp.getItemNo();
                costc=(double)p.getPrice()*no;
                
            }
        }
        lblCostText.setText(String.valueOf(costc));
    }
    
    public static long getDateDiff(long date1, long date2) {
        long diffInMillies = date2 - date1;
        System.out.println(diffInMillies);
        return diffInMillies / (60 * 1000);
    }
    
    private void checkoutDone() {
        
        if(!lblCostText.getText().equals("0.0")) {
            ArrayList<CartProduct> res = cust.getCartCatalogue().getCartCat();
            //Mark product sold
            for (CartProduct cp : res) {
                cp.getProduct().sold(cp.getItemNo());
                retCal.addToSoldList(cp);
                Calendar calendar1 = Calendar.getInstance();
                calendar1.add(Calendar.HOUR, 2);
                cp.setDiliveryTime(calendar1);
            }
            Admin.pay(cust.getCartCatalogue().getCartTotal());
            JOptionPane.showMessageDialog(null, "Items Ordered. Paid amount $" + cust.getCartCatalogue().getCartTotal());
            System.out.println("Tresury $" + Admin.getTreasury());
            cust.getPrevOrders().addCartToPrev(res);
            cust.setCartCatalogue(new CartCatalogue());
            backGo();
        } else {
            backGo();
            JOptionPane.showMessageDialog(null, "Nothing to order");
        }
    }
    
    private void backGo() {
        userProcessContainer.remove(this);
        Component[] componentArray = userProcessContainer.getComponents();
        Component component = componentArray[componentArray.length - 1];
        ViewBooked cm = (ViewBooked) component;
        cm.getallBookings();
        CardLayout layout= (CardLayout) userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblHeader = new javax.swing.JLabel();
        lblCost = new javax.swing.JLabel();
        lblCostText = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        txtCreditCardNo = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txtExpiry = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtCVV = new javax.swing.JTextField();
        btnCheckout = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtAddress = new javax.swing.JTextArea();

        lblHeader.setFont(new java.awt.Font("Lucida Grande", 1, 18)); // NOI18N
        lblHeader.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblHeader.setText("Checkout");

        lblCost.setText("Total Cost:");

        jLabel1.setText("Credit Card No.");

        jLabel2.setText("Expiry:");

        txtExpiry.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtExpiryActionPerformed(evt);
            }
        });

        jLabel3.setText("CVV:");

        btnCheckout.setFont(new java.awt.Font("Lucida Grande", 1, 14)); // NOI18N
        btnCheckout.setForeground(new java.awt.Color(0, 204, 153));
        btnCheckout.setText("Checkout");
        btnCheckout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCheckoutActionPerformed(evt);
            }
        });

        jLabel4.setText("Address:");

        txtAddress.setColumns(20);
        txtAddress.setRows(5);
        jScrollPane1.setViewportView(txtAddress);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblHeader, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(275, 275, 275)
                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(328, 328, 328)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel3))))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(328, 328, 328)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lblCost, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 39, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtCreditCardNo, javax.swing.GroupLayout.DEFAULT_SIZE, 344, Short.MAX_VALUE)
                                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 313, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtExpiry)
                                    .addComponent(txtCVV))))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblCostText, javax.swing.GroupLayout.DEFAULT_SIZE, 64, Short.MAX_VALUE)
                .addGap(218, 218, 218))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(552, Short.MAX_VALUE)
                .addComponent(btnCheckout, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(409, 409, 409))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblHeader, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lblCost, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblCostText, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(37, 37, 37)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(74, 74, 74)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtCreditCardNo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtExpiry, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtCVV, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(btnCheckout, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(144, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void txtExpiryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtExpiryActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtExpiryActionPerformed

    private void btnCheckoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCheckoutActionPerformed
       
        
        if((txtAddress.getText().equals(""))&(txtCVV.getText().equals(""))&(txtCreditCardNo.getText().equals(""))&(txtExpiry.getText().equals(""))) {
            JOptionPane.showMessageDialog(null, "Enter Fields");
        } else {
            boolean a1=Validate.stringCheck(txtAddress.getText(), "Address");
            boolean a2=Validate.integerCheck(txtCreditCardNo.getText(), "Credit Card Number");
            boolean a3=Validate.integerCheck(txtCVV.getText(), "CVV");
            boolean a4=Validate.stringCheck(txtExpiry.getText(), "Expriy");
        
            if(a1&&a2&&a3&&a4) {
                checkoutDone();
            }
        
        }
    }//GEN-LAST:event_btnCheckoutActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCheckout;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblCost;
    private javax.swing.JLabel lblCostText;
    private javax.swing.JLabel lblHeader;
    private javax.swing.JTextArea txtAddress;
    private javax.swing.JTextField txtCVV;
    private javax.swing.JTextField txtCreditCardNo;
    private javax.swing.JTextField txtExpiry;
    // End of variables declaration//GEN-END:variables
}
