/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interface.Customer;

import Business.Customer.CartProduct;
import Business.Customer.Customer;
import Business.Product;
import Business.Retailer.RetailerCatalogue;
import java.awt.CardLayout;
import java.text.DecimalFormat;
import java.util.ArrayList;
import java.util.Calendar;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author mahajan
 */
public class ViewBooked extends javax.swing.JPanel {

    /**
     * Creates new form ViewBooked
     */
    JPanel userProcessContainer;
    Customer cust;
    private RetailerCatalogue retCal;
    int nos=0;
    public ViewBooked(JPanel userProcessContainer, Customer cust, RetailerCatalogue retCal) {
        initComponents();
        this.userProcessContainer=userProcessContainer;
        this.cust=cust;
        this.retCal = retCal; 
        getallBookings();
        btnTrack.setEnabled(false);
        btnDelete.setEnabled(true);
        
    }
    
    public ViewBooked(JPanel userProcessContainer, Customer cust, int nos) {
        initComponents();
        this.userProcessContainer=userProcessContainer;
        this.cust=cust;
        getPrevBookings();
        if(nos!=0)
        {
            btnCheckOut.setEnabled(false);
            lblResult.setText("Previous Orders");
            btnTrack.setEnabled(true);
            btnDelete.setEnabled(false);
        }
        
    }
    

    public void getallBookings()
    {
        DefaultTableModel dtm = (DefaultTableModel)tblResult.getModel();
        dtm.setRowCount(0);
        
        ArrayList<Object[]> res;
        res= cust.getCart();
        if(res!=null)
        {
            for(Object[] ob:res)
            {
                Object[] tmp=new Object[4];
                tmp[0]=ob[0];
                tmp[1]=ob[1];
                dtm.addRow(tmp);
                
            }
        }
        
    }
    
    public void getPrevBookings()
    {
        DefaultTableModel dtm = (DefaultTableModel)tblResult.getModel();
        dtm.setRowCount(0);
        
        ArrayList<Object[]> res;
        res= cust.getPrevCart();
        if(res!=null)
        {
            for(Object[] ob:res)
            {
                Object[] tmp=new Object[4];
                tmp[0]=ob[0];
                tmp[1]=ob[1];
                dtm.addRow(tmp);
                
            }
        }
        
    }
    
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblResult = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblResult = new javax.swing.JTable();
        btnViewFlight = new javax.swing.JButton();
        btnBack = new javax.swing.JButton();
        btnCheckOut = new javax.swing.JButton();
        btnTrack = new javax.swing.JButton();
        btnDelete = new javax.swing.JButton();

        lblResult.setFont(new java.awt.Font("Lucida Grande", 1, 18)); // NOI18N
        lblResult.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblResult.setText("Summary");

        tblResult.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Product", "Number"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblResult.getTableHeader().setReorderingAllowed(false);
        jScrollPane1.setViewportView(tblResult);

        btnViewFlight.setText("View Details");
        btnViewFlight.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnViewFlightActionPerformed(evt);
            }
        });

        btnBack.setText("<<Back");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });

        btnCheckOut.setText("CheckOut");
        btnCheckOut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCheckOutActionPerformed(evt);
            }
        });

        btnTrack.setText("Track Item");
        btnTrack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTrackActionPerformed(evt);
            }
        });

        btnDelete.setText("Delete");
        btnDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(174, 174, 174)
                .addComponent(lblResult, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(174, 174, 174))
            .addGroup(layout.createSequentialGroup()
                .addComponent(btnBack)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnTrack, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGap(397, 397, 397))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnDelete, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGap(411, 411, 411)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnViewFlight, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnCheckOut, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addComponent(jScrollPane1))
                .addGap(35, 35, 35))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblResult, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 281, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnViewFlight)
                    .addComponent(btnTrack))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCheckOut)
                    .addComponent(btnDelete))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 41, Short.MAX_VALUE)
                .addComponent(btnBack))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnViewFlightActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnViewFlightActionPerformed

        int getSelected= tblResult.getSelectedRow();
        if(getSelected>=0)
        {
            Product arer =new Product();
            arer=(Product)tblResult.getValueAt(getSelected, 0);
            CartProduct itemnos= (CartProduct) tblResult.getValueAt(getSelected, 1);
            ViewProduct vfl = new ViewProduct(userProcessContainer, arer,itemnos.getItemNo());
            userProcessContainer.add("viewcart",vfl);
            CardLayout layout = (CardLayout)userProcessContainer.getLayout();
            layout.next(userProcessContainer);
        }
        else
            JOptionPane.showMessageDialog(null, "Select Row", "Error", 0);
    }//GEN-LAST:event_btnViewFlightActionPerformed

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        userProcessContainer.remove(this);
        CardLayout layout= (CardLayout) userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
    }//GEN-LAST:event_btnBackActionPerformed

    private void btnCheckOutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCheckOutActionPerformed
        
        
        CheckoutPanel cm= new CheckoutPanel(userProcessContainer,cust, retCal);
        userProcessContainer.add("CheckoutCart",cm);
        CardLayout layout = (CardLayout)userProcessContainer.getLayout();
        layout.next(userProcessContainer);
        
        //getallBookings();
    }//GEN-LAST:event_btnCheckOutActionPerformed

    public static long getDateDiff(long date1, long date2) {
        long diffInMillies = date2 - date1;
        System.out.println(diffInMillies);
        return diffInMillies / (60 * 1000);
    }
    
    private void btnTrackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTrackActionPerformed
        
        int getSelected= tblResult.getSelectedRow();
        if(getSelected>=0)
        { 
            //int range=2;
            
            CartProduct cp=(CartProduct)tblResult.getValueAt(getSelected, 1);
            System.out.println(getDateDiff(cp.getDiliveryTime().getTimeInMillis(), Calendar.getInstance().getTimeInMillis()));
            double a= Math.random()+1;
            
            JOptionPane.showMessageDialog(null, " Product Will be Delivered in "+new DecimalFormat("##.##").format(a)+" hrs");
        }
        else
            JOptionPane.showMessageDialog(null, "Select Row", "Error", 0);
   
    }//GEN-LAST:event_btnTrackActionPerformed

    private void btnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteActionPerformed
        
        int getSelected= tblResult.getSelectedRow();
        Product arer;
        CartProduct cp;
        //Validate vl=new Validate();
        
            if(getSelected>=0)
            {
                
                
                arer=(Product)tblResult.getValueAt(getSelected, 0);
                cp=(CartProduct)tblResult.getValueAt(getSelected, 1);
                cust.getCartCatalogue().remCartCat(cp);
                
                int total=cp.getItemNo();
                arer.setAvailableUnits(arer.getAvailableUnits()+total);
                getallBookings();
            
            }
        
        
        
        
    }//GEN-LAST:event_btnDeleteActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnCheckOut;
    private javax.swing.JButton btnDelete;
    private javax.swing.JButton btnTrack;
    private javax.swing.JButton btnViewFlight;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblResult;
    private javax.swing.JTable tblResult;
    // End of variables declaration//GEN-END:variables
}
