/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UI.TravelAgent;

import Business.FleetCatalogue;
import Business.Flight;
import Business.Operator;
import Business.OperatorCatalogue;
import UI.Operator.ViewFlight;
import java.awt.CardLayout;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author mahajan
 */
public class mtsPanel extends javax.swing.JPanel {

    private OperatorCatalogue operatorCat;
    JPanel userProcessContainer;
    
    mtsPanel(JPanel userProcessContainer, OperatorCatalogue operatorCat) {
        initComponents();
        this.operatorCat=operatorCat;
        this.userProcessContainer=userProcessContainer;
        populateTable();
    }

    
    
    private void populateTable()
    {
        DefaultTableModel dtm = (DefaultTableModel)tblMTS.getModel();
        dtm.setRowCount(0);
        
        for(Operator op:operatorCat.getOpCat())
        {
            for(Flight ff: op.getFleetCat().getFleetCat())
            {
                Object[] ob= new Object[4];
                ob[0]=op;
                ob[1]=ff;
                ob[2]=ff.getFromLoc();
                ob[3]=ff.getToLoc();
                dtm.addRow(ob);
            }
        }
        
        
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tblMTS = new javax.swing.JTable();
        lblMTS = new javax.swing.JLabel();
        btnViewFlight = new javax.swing.JButton();
        btnBack = new javax.swing.JButton();

        tblMTS.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Operator", "ID", "From", "To"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tblMTS);
        if (tblMTS.getColumnModel().getColumnCount() > 0) {
            tblMTS.getColumnModel().getColumn(0).setResizable(false);
            tblMTS.getColumnModel().getColumn(1).setResizable(false);
            tblMTS.getColumnModel().getColumn(2).setResizable(false);
            tblMTS.getColumnModel().getColumn(3).setResizable(false);
        }

        lblMTS.setFont(new java.awt.Font("Lucida Grande", 1, 18)); // NOI18N
        lblMTS.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblMTS.setText("Master Travel Schedule");

        btnViewFlight.setText("View Flight");
        btnViewFlight.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnViewFlightActionPerformed(evt);
            }
        });

        btnBack.setText("<<Back");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(174, 174, 174)
                .addComponent(lblMTS, javax.swing.GroupLayout.DEFAULT_SIZE, 297, Short.MAX_VALUE)
                .addGap(174, 174, 174))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnViewFlight))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(33, 33, 33)
                        .addComponent(jScrollPane1)))
                .addGap(35, 35, 35))
            .addGroup(layout.createSequentialGroup()
                .addComponent(btnBack)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblMTS, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 285, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnViewFlight)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnBack))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        userProcessContainer.remove(this);
        CardLayout layout= (CardLayout) userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
        
        
    }//GEN-LAST:event_btnBackActionPerformed

    private void btnViewFlightActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnViewFlightActionPerformed
        
        int getSelected= tblMTS.getSelectedRow();
        if(getSelected>=0)
        {
            Flight arer=new Flight();
            arer=(Flight)tblMTS.getValueAt(getSelected, 1);
            ViewFlight vfl = new ViewFlight(userProcessContainer, arer);
            userProcessContainer.add("AddAirplane",vfl);
            CardLayout layout = (CardLayout)userProcessContainer.getLayout();
            layout.next(userProcessContainer);
        }
        else
        {
            JOptionPane.showMessageDialog(null, "Select Row", "Error", 0);
        }
        
        
    }//GEN-LAST:event_btnViewFlightActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnViewFlight;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblMTS;
    private javax.swing.JTable tblMTS;
    // End of variables declaration//GEN-END:variables
}
