/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interface;

import BusinessLogic.Cars;
import BusinessLogic.CarsArray;
import java.util.regex.Pattern;
import javax.swing.ButtonGroup;
import javax.swing.JOptionPane;
import javax.swing.JRadioButton;

/**
 *
 * @author mahajan
 */
public class CreatePanel extends javax.swing.JPanel {

    /**
     * Creates new form CreatePanel
     */
    private int error;
    private CarsArray carsArray;
    
    ButtonGroup BTNgrp;    
        
    public CreatePanel(CarsArray carsArray) {
        initComponents();
        this.carsArray=carsArray;
        
        
        unavailableRadio.setSelected(true);
        //Group the radio buttons.
        BTNgrp= new ButtonGroup();
        BTNgrp.add(availableRadio);
        BTNgrp.add(unavailableRadio);
        
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        addCarLbl = new javax.swing.JLabel();
        createButton = new javax.swing.JButton();
        manufacturerLBL = new javax.swing.JLabel();
        manufacturer = new javax.swing.JTextField();
        modelNameLBL = new javax.swing.JLabel();
        modelName = new javax.swing.JTextField();
        modelNumberLBL = new javax.swing.JLabel();
        manufactureYearLBL = new javax.swing.JLabel();
        cityLBL = new javax.swing.JLabel();
        serialNumberLBL = new javax.swing.JLabel();
        modelNumber = new javax.swing.JTextField();
        manufactureYear = new javax.swing.JTextField();
        city = new javax.swing.JTextField();
        serialNumber = new javax.swing.JTextField();
        certificateExpiryLBL = new javax.swing.JLabel();
        certificateExpiry = new javax.swing.JTextField();
        minSeatLBL = new javax.swing.JLabel();
        minSeat = new javax.swing.JTextField();
        maxSearLBL = new javax.swing.JLabel();
        maxSeat = new javax.swing.JTextField();
        availableRadio = new javax.swing.JRadioButton();
        unavailableRadio = new javax.swing.JRadioButton();

        addCarLbl.setFont(new java.awt.Font("Lucida Grande", 0, 24)); // NOI18N
        addCarLbl.setText("UBER Add Car");

        createButton.setText("Add Car");
        createButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                createButtonActionPerformed(evt);
            }
        });

        manufacturerLBL.setText("Manufacturer");

        modelNameLBL.setText("Model Name");

        modelName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                modelNameActionPerformed(evt);
            }
        });

        modelNumberLBL.setText("Model Number");

        manufactureYearLBL.setText("Manufacture Year");

        cityLBL.setText("City");

        serialNumberLBL.setText("Serial Number");

        certificateExpiryLBL.setText("Maintainence Certificate Expiry: ");

        minSeatLBL.setText("Minimum Seat");

        maxSearLBL.setText("Maximum Seat");

        availableRadio.setText("Available");
        availableRadio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                availableRadioActionPerformed(evt);
            }
        });

        unavailableRadio.setText("UnAvailable");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(75, 75, 75)
                .addComponent(createButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(69, 69, 69))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(certificateExpiryLBL)
                .addGap(18, 18, 18)
                .addComponent(certificateExpiry)
                .addGap(14, 14, 14))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(modelNumberLBL)
                    .addComponent(cityLBL)
                    .addComponent(modelNameLBL)
                    .addComponent(minSeatLBL))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(modelName)
                    .addComponent(city)
                    .addComponent(modelNumber)
                    .addComponent(minSeat, javax.swing.GroupLayout.DEFAULT_SIZE, 155, Short.MAX_VALUE))
                .addGap(64, 64, 64)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(manufacturerLBL)
                    .addComponent(manufactureYearLBL)
                    .addComponent(serialNumberLBL)
                    .addComponent(maxSearLBL))
                .addGap(18, 18, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(manufacturer, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(14, 14, 14))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(manufactureYear, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(serialNumber, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(maxSeat, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap())))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(225, 225, 225)
                        .addComponent(addCarLbl))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(264, 264, 264)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(unavailableRadio)
                            .addComponent(availableRadio))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(addCarLbl)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(manufacturerLBL)
                    .addComponent(manufacturer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(modelNameLBL)
                    .addComponent(modelName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(modelNumberLBL)
                    .addComponent(manufactureYearLBL)
                    .addComponent(modelNumber, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(manufactureYear, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(17, 17, 17)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cityLBL)
                    .addComponent(serialNumberLBL)
                    .addComponent(city, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(serialNumber, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(minSeatLBL)
                    .addComponent(minSeat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(maxSearLBL)
                    .addComponent(maxSeat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(certificateExpiryLBL)
                    .addComponent(certificateExpiry, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 39, Short.MAX_VALUE)
                .addComponent(availableRadio)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(unavailableRadio)
                .addGap(18, 18, 18)
                .addComponent(createButton)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void createButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_createButtonActionPerformed
        // TODO add your handling code here:
       createAction();

    }//GEN-LAST:event_createButtonActionPerformed

    
    private void createAction()
    {
        error=0;
        String modelNum= modelNumber.getText();
        String mod= modelName.getText();
        String manuf= manufacturer.getText();
        String manufYr= manufactureYear.getText();
        String cIty=city.getText();
        String certExp= certificateExpiry.getText();
        String serNO= serialNumber.getText();
        String maxiSeat=maxSeat.getText();
        String miniSeat= minSeat.getText();
        Boolean avail;
        
        
        if(BTNgrp.getSelection()==availableRadio.getModel())
        {
            avail= true ;
        }
        else
        {
            avail= false;
        }
        
        
        integerCheck(modelNum, "Model Number");
        stringCheck(mod,"Model Name");
        stringCheck(manuf, "Manufacturer");
        dateCheck(manufYr,"Manufacture Year");
        stringCheck(cIty, "City");
        dateCheck(certExp, "Certificate Expiry");
        integerCheck(serNO, "Serial Number");
        integerCheck(maxiSeat, "Maximum Seat");
        integerCheck(miniSeat,"Minimum Seat");
        
        if(Integer.parseInt(miniSeat)>Integer.parseInt(maxiSeat))
        {
            error=1;
            JOptionPane.showMessageDialog(null, "Maximum Seat Should be more than Minimum seat", "Error", 0);
        }
        

        if(error!=1)
        {
            Cars car=new Cars();
            
            car.setCity(cIty);
            car.setAvailability(avail);
            car.setCertificateExpiry(certExp);
            car.setManifactureYear(manufYr);
            car.setManufacturer(manuf);
            car.setMaxSeat(Integer.parseInt(maxiSeat));
            car.setMinSeat(Integer.parseInt(miniSeat));
            car.setModelName(mod);
            car.setModelNumber(modelNum);
            car.setSerialNumber(serNO);
            
            carsArray.addCarsArray(car);
            JOptionPane.showMessageDialog(null, "Data Recorded Successfully");
            
            modelName.setText("");
            modelNumber.setText("");
            manufactureYear.setText("");
            manufacturer.setText("");
            serialNumber.setText("");
            maxSeat.setText("");
            minSeat.setText("");
            city.setText("");
            serialNumber.setText("");
            certificateExpiry.setText("");
                    
            
            
            
        }
    }
    
    
    
    
    private void integerCheck(String checkThis, String field)
    {
        try
        {
            if(Double.parseDouble(checkThis)%1!=0)
            {
                error=1;
                JOptionPane.showMessageDialog(null, field+" should not be in fraction","ERROR",0);
            }
            
        }
        catch(Exception e)
        {
            error=1;
            JOptionPane.showMessageDialog(null, field+" should be in Number format","ERR0R",0);       
        }
    }
    
    
    private void stringCheck(String checkThis, String field)
    {
        try
        {
            if(Double.valueOf(Double.parseDouble(checkThis))>=0);
            {
                error=1;
                JOptionPane.showMessageDialog(null,"Please enter "+field +" in proper format", "Error", 0);
            }
        }
        catch(Exception e){}
        
    }
    
    private void dateCheck(String checkThis, String field)
    {
         try
        {
            if(Double.valueOf(Double.parseDouble(checkThis))>=0);
            {
                error=1;
                JOptionPane.showMessageDialog(null,"Please enter "+field +"Date in proper format", "Error", 0);
            }
        }
        catch(Exception e)
        {
                if(!getDateRegex(checkThis))
                {
                    error=1;
                    JOptionPane.showMessageDialog(null,"Please Enter "+field+"date in format MM-DD-YYYY","ERROR",0);
                }    
                    
                    
        }
        
    }
    
    private boolean getDateRegex(String date)
    {
        //String regex= "\\d{2}\\-\\d{2}\\-\\d{4}";
        String dRegex="^(0[0-9]|1[0-2])\\-(0[1-9]|1[0-9]|2[0-9]|3[0-1])\\-(199[0-9]|20[0-1][0-8])";
        final Pattern pattern = Pattern.compile(dRegex);
        boolean bool=pattern.matcher(date).matches();
        return bool;
            
    }
    
    
    
    
    
    private void modelNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_modelNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_modelNameActionPerformed

    private void availableRadioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_availableRadioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_availableRadioActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel addCarLbl;
    private javax.swing.JRadioButton availableRadio;
    private javax.swing.JTextField certificateExpiry;
    private javax.swing.JLabel certificateExpiryLBL;
    private javax.swing.JTextField city;
    private javax.swing.JLabel cityLBL;
    private javax.swing.JButton createButton;
    private javax.swing.JTextField manufactureYear;
    private javax.swing.JLabel manufactureYearLBL;
    private javax.swing.JTextField manufacturer;
    private javax.swing.JLabel manufacturerLBL;
    private javax.swing.JLabel maxSearLBL;
    private javax.swing.JTextField maxSeat;
    private javax.swing.JTextField minSeat;
    private javax.swing.JLabel minSeatLBL;
    private javax.swing.JTextField modelName;
    private javax.swing.JLabel modelNameLBL;
    private javax.swing.JTextField modelNumber;
    private javax.swing.JLabel modelNumberLBL;
    private javax.swing.JTextField serialNumber;
    private javax.swing.JLabel serialNumberLBL;
    private javax.swing.JRadioButton unavailableRadio;
    // End of variables declaration//GEN-END:variables
}
