/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interface.Admin;

import Business.Admin;
import Business.Retailer.Retailer;
import Business.Validation.Validate;
import java.awt.CardLayout;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author karanracca
 */
public class MainAdminPanel extends javax.swing.JPanel {

    /**
     * Creates new form MainAdminPanel
     */
    
    private JPanel cards;
    private Admin masterClass;
    
    public MainAdminPanel(JPanel Cards, Admin masterClass) {
        initComponents();
        this.cards = Cards;
        this.masterClass = masterClass;
        populateTable(masterClass.getRetailerCatalogue().getRetailerCatalogue());
    }
    
    private void populateTable(ArrayList<Retailer> list) {
        DefaultTableModel dtm = (DefaultTableModel) retailerTable.getModel();
        dtm.setRowCount(0);

        for (Retailer r : list) {
            Object row[] = new Object[5];
            row[0] = r.getRetailerNumber();
            row[1] = r;
            row[2] = r.getZipCode();
            row[3] = r.getProductCatalogue().getTotalSoldCount();
            row[4] = r.getEarnings();
            dtm.addRow(row);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        headingAdmin = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        retailerTable = new javax.swing.JTable();
        addRetailerBtn = new javax.swing.JButton();
        deleteAirlinerBtn = new javax.swing.JButton();
        backBtn = new javax.swing.JButton();
        selectBtn = new javax.swing.JButton();
        zipTF = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        clearBtn = new javax.swing.JButton();
        viewDataBtn1 = new javax.swing.JButton();
        invoiceListBtn = new javax.swing.JButton();

        addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                formComponentShown(evt);
            }
        });

        headingAdmin.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        headingAdmin.setText("Welcome Admin");

        retailerTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Retailer Number", "Retailer Name", "Zip Code", "Total Products Sold", "Total Earnings"
            }
        ));
        jScrollPane1.setViewportView(retailerTable);

        addRetailerBtn.setText("Add New Retailer");
        addRetailerBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addRetailerBtnActionPerformed(evt);
            }
        });

        deleteAirlinerBtn.setForeground(new java.awt.Color(255, 51, 51));
        deleteAirlinerBtn.setText("Delete Retailer");
        deleteAirlinerBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteAirlinerBtnActionPerformed(evt);
            }
        });

        backBtn.setForeground(new java.awt.Color(255, 0, 0));
        backBtn.setText("Logout");
        backBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backBtnActionPerformed(evt);
            }
        });

        selectBtn.setText("Select");
        selectBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                selectBtnActionPerformed(evt);
            }
        });

        jButton1.setText("Search By Zip");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        clearBtn.setText("Clear");
        clearBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clearBtnActionPerformed(evt);
            }
        });

        viewDataBtn1.setText("View Customer Data");
        viewDataBtn1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewDataBtn1ActionPerformed(evt);
            }
        });

        invoiceListBtn.setText("View Invoice List");
        invoiceListBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                invoiceListBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(viewDataBtn1, javax.swing.GroupLayout.PREFERRED_SIZE, 189, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(invoiceListBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 189, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(backBtn)
                                .addGap(0, 0, Short.MAX_VALUE))))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(deleteAirlinerBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 189, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(9, 9, 9)
                                .addComponent(zipTF, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(addRetailerBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 189, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(397, 397, 397)
                        .addComponent(selectBtn)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 340, Short.MAX_VALUE)
                        .addComponent(clearBtn))
                    .addComponent(headingAdmin, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(headingAdmin, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 221, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(selectBtn)
                    .addComponent(clearBtn))
                .addGap(18, 18, 18)
                .addComponent(addRetailerBtn)
                .addGap(18, 18, 18)
                .addComponent(deleteAirlinerBtn)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(zipTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(viewDataBtn1)
                .addGap(18, 18, 18)
                .addComponent(invoiceListBtn)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 23, Short.MAX_VALUE)
                .addComponent(backBtn)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void addRetailerBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addRetailerBtnActionPerformed
        AddRetailerPanel addRetailer = new AddRetailerPanel(cards, masterClass.getRetailerCatalogue(), masterClass.getUserAccountDirectory());
        cards.add("AddRetailerJPanel", addRetailer);
        CardLayout cLayout = (CardLayout) cards.getLayout();
        cLayout.next(cards);
    }//GEN-LAST:event_addRetailerBtnActionPerformed

    private void deleteAirlinerBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteAirlinerBtnActionPerformed
        if (retailerTable.getSelectedRow() >= 0) {
            Retailer r = (Retailer) retailerTable.getValueAt(retailerTable.getSelectedRow(), 1);
            masterClass.getRetailerCatalogue().removeRetailer(r);
            populateTable(masterClass.getRetailerCatalogue().getRetailerCatalogue());

        } else {
            JOptionPane.showMessageDialog(null, "Please select a row");
        }
    }//GEN-LAST:event_deleteAirlinerBtnActionPerformed

    private void backBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backBtnActionPerformed
        cards.remove(this);
        CardLayout cLayout = (CardLayout) cards.getLayout();
        cLayout.previous(cards);
    }//GEN-LAST:event_backBtnActionPerformed

    private void selectBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_selectBtnActionPerformed
        if (retailerTable.getSelectedRow() >= 0) {
            Retailer r = (Retailer) retailerTable.getValueAt(retailerTable.getSelectedRow(), 1);
            ViewRetailerPanel viewJPanel = new ViewRetailerPanel(cards, r);
            cards.add("ViewRetailerPanel", viewJPanel);
            CardLayout cLayout = (CardLayout) cards.getLayout();
            cLayout.next(cards);

        } else {
            JOptionPane.showMessageDialog(null, "Please select a row");
        }
    }//GEN-LAST:event_selectBtnActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        if (Validate.integerCheck(zipTF.getText(), "Zip")) {
            ArrayList<Retailer> searchResult = masterClass.getRetailerCatalogue().searchByZip(zipTF.getText());
            populateTable(searchResult);
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void clearBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clearBtnActionPerformed
       populateTable(masterClass.getRetailerCatalogue().getRetailerCatalogue());
    }//GEN-LAST:event_clearBtnActionPerformed

    private void viewDataBtn1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewDataBtn1ActionPerformed
        ViewDataPanel viewJPanel = new ViewDataPanel(cards, masterClass);
        cards.add("ViewdDataPanel", viewJPanel);
        CardLayout cLayout = (CardLayout) cards.getLayout();
        cLayout.next(cards);
    }//GEN-LAST:event_viewDataBtn1ActionPerformed

    private void invoiceListBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_invoiceListBtnActionPerformed
        InvoicePanel invoicePanel = new InvoicePanel(cards, masterClass.getRetailerCatalogue());
        cards.add("InvoicePanel", invoicePanel);
        CardLayout cLayout = (CardLayout) cards.getLayout();
        cLayout.next(cards);
    }//GEN-LAST:event_invoiceListBtnActionPerformed

    private void formComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_formComponentShown
        populateTable(masterClass.getRetailerCatalogue().getRetailerCatalogue());
    }//GEN-LAST:event_formComponentShown


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addRetailerBtn;
    private javax.swing.JButton backBtn;
    private javax.swing.JButton clearBtn;
    private javax.swing.JButton deleteAirlinerBtn;
    private javax.swing.JLabel headingAdmin;
    private javax.swing.JButton invoiceListBtn;
    private javax.swing.JButton jButton1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable retailerTable;
    private javax.swing.JButton selectBtn;
    private javax.swing.JButton viewDataBtn1;
    private javax.swing.JTextField zipTF;
    // End of variables declaration//GEN-END:variables
}
