/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interface.Admin;

import Business.Product;
import Business.Retailer.ProductCatalogue;
import Business.Retailer.Retailer;
import Interface.Retailer.ViewUpdateProduct;
import java.awt.CardLayout;
import java.util.Collections;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author karanracca
 */
public class ViewRetailerPanel extends javax.swing.JPanel {

    /**
     * Creates new form ViewRetailerPanel
     */
    private JPanel cards;
    private Retailer retailer;

    ViewRetailerPanel(JPanel cards, Retailer r) {
        initComponents();
        this.cards = cards;
        this.retailer = r;
        retailerNameLbl.setText(this.retailer.getRetailerName());
        zipCodeLbl.setText("Zip Code - "+ this.retailer.getZipCode());
        populateProducts();
        if (retailer.getProductCatalogue().getMostProductSold() != null) {
            maxProductSold.setText("Maximum product sold-- "+retailer.getProductCatalogue().getMostProductSold().getProductName());
        }
        
        if (retailer.getProductCatalogue().getLeastProductSold() != null) {
            minProductSold.setText("Minimum product sold-- "+retailer.getProductCatalogue().getLeastProductSold().getProductName());
        }
    }
    
    private void populateProducts() {
        DefaultTableModel dtm = (DefaultTableModel) retailerProductsTable.getModel();
        dtm.setRowCount(0);

        for (Product p : retailer.getProductCatalogue().getProductCatalogue()) {
            Object row[] = new Object[5];
            row[0] = p.getProductNumber();
            row[1] = p;
            row[2] = p.getPrice();
            row[3] = p.getSoldNumber();
            row[4] = (p.getSoldNumber()*p.getPrice());
            dtm.addRow(row);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        retailerNameLbl = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        retailerProductsTable = new javax.swing.JTable();
        selectBtn = new javax.swing.JButton();
        backBtn = new javax.swing.JButton();
        zipCodeLbl = new javax.swing.JLabel();
        maxProductSold = new javax.swing.JLabel();
        minProductSold = new javax.swing.JLabel();
        sortProductSold = new javax.swing.JButton();
        sortSalePrice = new javax.swing.JButton();

        retailerNameLbl.setFont(new java.awt.Font("Lucida Grande", 1, 14)); // NOI18N
        retailerNameLbl.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        retailerNameLbl.setText("Retailer Name");
        retailerNameLbl.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        retailerProductsTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Product Number", "Product Name", "Product Price", "Number of Items Sold", "Total sale price"
            }
        ));
        jScrollPane1.setViewportView(retailerProductsTable);

        selectBtn.setText("Select");
        selectBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                selectBtnActionPerformed(evt);
            }
        });

        backBtn.setText("< Back");
        backBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backBtnActionPerformed(evt);
            }
        });

        zipCodeLbl.setText("Zip Code");

        maxProductSold.setText("Maximum Product Sold -- ");

        minProductSold.setText("Least Product Sold --");

        sortProductSold.setText("Sort by Products Sold");
        sortProductSold.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sortProductSoldActionPerformed(evt);
            }
        });

        sortSalePrice.setText("Sort by Total Sale Price");
        sortSalePrice.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sortSalePriceActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(backBtn)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(retailerNameLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 707, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(zipCodeLbl)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(418, Short.MAX_VALUE)
                .addComponent(selectBtn)
                .addGap(401, 401, 401))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(minProductSold)
                            .addComponent(maxProductSold)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(16, 16, 16)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(sortSalePrice)
                            .addComponent(sortProductSold))))
                .addContainerGap(697, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(retailerNameLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(zipCodeLbl))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 194, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(selectBtn)
                .addGap(26, 26, 26)
                .addComponent(maxProductSold)
                .addGap(18, 18, 18)
                .addComponent(minProductSold)
                .addGap(18, 18, 18)
                .addComponent(sortProductSold)
                .addGap(18, 18, 18)
                .addComponent(sortSalePrice)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 84, Short.MAX_VALUE)
                .addComponent(backBtn)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void selectBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_selectBtnActionPerformed
        if (retailerProductsTable.getSelectedRow() >= 0) {
            Product p = (Product) retailerProductsTable.getValueAt(retailerProductsTable.getSelectedRow(), 1);
              ViewUpdateProduct vup = new ViewUpdateProduct(cards, p, 1);
              cards.add("ViewUpdateProduct", vup);
              CardLayout cLayout = (CardLayout) cards.getLayout();
              cLayout.next(cards);
        } else {
            JOptionPane.showMessageDialog(null, "Please select a row");
        }

    }//GEN-LAST:event_selectBtnActionPerformed

    private void backBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backBtnActionPerformed
        cards.remove(this);
        CardLayout cLayout = (CardLayout) cards.getLayout();
        cLayout.previous(cards);
    }//GEN-LAST:event_backBtnActionPerformed

    private void sortProductSoldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sortProductSoldActionPerformed
        Collections.sort(retailer.getProductCatalogue().getProductCatalogue(), ProductCatalogue.ByProductsSold);
        populateProducts();
    }//GEN-LAST:event_sortProductSoldActionPerformed

    private void sortSalePriceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sortSalePriceActionPerformed
        Collections.sort(retailer.getProductCatalogue().getProductCatalogue(), ProductCatalogue.BySalePrice);
        populateProducts();
    }//GEN-LAST:event_sortSalePriceActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton backBtn;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel maxProductSold;
    private javax.swing.JLabel minProductSold;
    private javax.swing.JLabel retailerNameLbl;
    private javax.swing.JTable retailerProductsTable;
    private javax.swing.JButton selectBtn;
    private javax.swing.JButton sortProductSold;
    private javax.swing.JButton sortSalePrice;
    private javax.swing.JLabel zipCodeLbl;
    // End of variables declaration//GEN-END:variables
}
