/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interface.Admin;

import Business.Retailer.Retailer;
import Business.Retailer.RetailerCatalogue;
import Business.UserAccount;
import Business.UserAccountDirectory;
import Business.Validation.Validate;
import java.awt.CardLayout;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author karanracca
 */
public class AddRetailerPanel extends javax.swing.JPanel {

    /**
     * Creates new form AddRetailerPanel
     */
    private JPanel cards;
    private RetailerCatalogue retailerCatalogue;
    private UserAccountDirectory userAccountDirectory;

    AddRetailerPanel(JPanel cards, RetailerCatalogue retailerCatalogue, UserAccountDirectory userAccountDirectory) {
        initComponents();
        this.cards = cards;
        this.retailerCatalogue = retailerCatalogue;
        this.userAccountDirectory = userAccountDirectory;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        newAirlinerLbl = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        nameTF = new javax.swing.JTextField();
        headQLbl = new javax.swing.JLabel();
        zipTF = new javax.swing.JTextField();
        saveBtn = new javax.swing.JButton();
        cancelBtn = new javax.swing.JButton();
        headQLbl1 = new javax.swing.JLabel();
        usernameTF = new javax.swing.JTextField();
        headQLbl2 = new javax.swing.JLabel();
        passwordTF = new javax.swing.JTextField();

        newAirlinerLbl.setFont(new java.awt.Font("Lucida Grande", 1, 14)); // NOI18N
        newAirlinerLbl.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        newAirlinerLbl.setText("Register New Retailer");
        newAirlinerLbl.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        jLabel1.setText("Name of the Retailer");

        headQLbl.setText("Zip Code");

        saveBtn.setForeground(new java.awt.Color(51, 153, 0));
        saveBtn.setText("Register");
        saveBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveBtnActionPerformed(evt);
            }
        });

        cancelBtn.setText("Cancel");
        cancelBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelBtnActionPerformed(evt);
            }
        });

        headQLbl1.setText("Username");

        headQLbl2.setText("Password");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(newAirlinerLbl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGap(314, 314, 314)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(headQLbl)
                            .addComponent(headQLbl1)
                            .addComponent(headQLbl2))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(zipTF, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(nameTF, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(usernameTF, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(passwordTF, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 234, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(346, 346, 346)
                .addComponent(saveBtn)
                .addGap(41, 41, 41)
                .addComponent(cancelBtn)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(newAirlinerLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(nameTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(headQLbl)
                    .addComponent(zipTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(16, 16, 16)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(headQLbl1)
                    .addComponent(usernameTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(headQLbl2)
                    .addComponent(passwordTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(82, 82, 82)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(saveBtn)
                    .addComponent(cancelBtn))
                .addGap(0, 258, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void saveBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveBtnActionPerformed
        if (!nameTF.getText().isEmpty() && !zipTF.getText().isEmpty()) {
            if (Validate.stringCheck(nameTF.getText(), "Name") && Validate.integerCheck(zipTF.getText(), "Zip Code") && Validate.stringCheck(usernameTF.getText(), "Username")) {
                Retailer r = new Retailer();
                r.setRetailerName(nameTF.getText());
                r.setZipCode(zipTF.getText());
                retailerCatalogue.addRetailer(r);

                UserAccount ua = new UserAccount(usernameTF.getText(), passwordTF.getText(), UserAccount.RETAILER_ROLE, r);
                userAccountDirectory.addUserAccount(ua);
                JOptionPane.showMessageDialog(null, "New Retailer Added");
                //Move back to Manage Airliner.
                cards.remove(this);
                CardLayout cLayout = (CardLayout) cards.getLayout();
                cLayout.previous(cards);
            }

        } else {
            JOptionPane.showMessageDialog(null, "Please enter all value");
        }
    }//GEN-LAST:event_saveBtnActionPerformed

    private void cancelBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelBtnActionPerformed
        cards.remove(this);
        CardLayout cLayout = (CardLayout) cards.getLayout();
        cLayout.previous(cards);
    }//GEN-LAST:event_cancelBtnActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cancelBtn;
    private javax.swing.JLabel headQLbl;
    private javax.swing.JLabel headQLbl1;
    private javax.swing.JLabel headQLbl2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JTextField nameTF;
    private javax.swing.JLabel newAirlinerLbl;
    private javax.swing.JTextField passwordTF;
    private javax.swing.JButton saveBtn;
    private javax.swing.JTextField usernameTF;
    private javax.swing.JTextField zipTF;
    // End of variables declaration//GEN-END:variables
}
