/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interface.Admin;

import Business.Admin;
import Business.Retailer.Retailer;
import Business.Retailer.RetailerCatalogue;
import Business.Retailer.RetailerInvoice;
import java.awt.CardLayout;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author karanracca
 */
public class InvoicePanel extends javax.swing.JPanel {

    /**
     * Creates new form InvoicePanel
     */
    private JPanel cards;
    private RetailerCatalogue retailerCatalogue;
    
    InvoicePanel(JPanel cards, RetailerCatalogue retailerCatalogue) {
        initComponents();
        this.cards = cards;
        this.retailerCatalogue = retailerCatalogue;
        populateInvoiceTbl();
        updateTresury();
    }
    
    private void populateInvoiceTbl() {
        DefaultTableModel dtm = (DefaultTableModel) invoiceListTbl.getModel();
        dtm.setRowCount(0);
        
        for (Retailer r : retailerCatalogue.getRetailerCatalogue()) {
            for (RetailerInvoice ri : r.getRetailerInvoiceList().getInvoiceList()) {
                if (!ri.isPaid()) {
                    Object row[] = new Object[5];
                    row[0] = r.getRetailerNumber();
                    row[1] = r;
                    row[2] = ri;
                    row[3] = ri.getCartProductsSold().getCartCat().size();
                    row[4] = ri.getTotalPriceToBePaid();
                    dtm.addRow(row);
                }
            }
        }
        updateTresury();
    }
    
    private void updateTresury() {
        amountLbl.setText(String.valueOf(Admin.getTreasury()));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        headingAdmin = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        invoiceListTbl = new javax.swing.JTable();
        payBtn = new javax.swing.JButton();
        backBtn = new javax.swing.JButton();
        treasuryLbl = new javax.swing.JLabel();
        amountLbl = new javax.swing.JLabel();

        addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                formComponentShown(evt);
            }
        });

        headingAdmin.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        headingAdmin.setText("Invoice List");

        invoiceListTbl.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Retailer Number", "Retailer Name", "Invoive Number", "Total Products", "Invoice Amount"
            }
        ));
        jScrollPane1.setViewportView(invoiceListTbl);

        payBtn.setText("Pay");
        payBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                payBtnActionPerformed(evt);
            }
        });

        backBtn.setForeground(new java.awt.Color(255, 0, 0));
        backBtn.setText("Back");
        backBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backBtnActionPerformed(evt);
            }
        });

        treasuryLbl.setFont(new java.awt.Font("Lucida Grande", 1, 14)); // NOI18N
        treasuryLbl.setText("Treasury");

        amountLbl.setFont(new java.awt.Font("Lucida Grande", 1, 24)); // NOI18N
        amountLbl.setText("amount");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(treasuryLbl)
                .addGap(18, 18, 18)
                .addComponent(amountLbl)
                .addContainerGap(715, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addContainerGap()
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(headingAdmin, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(backBtn)
                            .addGap(0, 0, Short.MAX_VALUE))
                        .addGroup(layout.createSequentialGroup()
                            .addGap(397, 397, 397)
                            .addComponent(payBtn)
                            .addGap(416, 416, 416)))
                    .addContainerGap()))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(333, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(treasuryLbl)
                    .addComponent(amountLbl))
                .addGap(237, 237, 237))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(headingAdmin, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 221, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                    .addComponent(payBtn)
                    .addGap(246, 246, 246)
                    .addComponent(backBtn)
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void payBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_payBtnActionPerformed
        if (invoiceListTbl.getSelectedRow() >= 0) {
            RetailerInvoice ri = (RetailerInvoice) invoiceListTbl.getValueAt(invoiceListTbl.getSelectedRow(), 2);
            Retailer r = (Retailer) invoiceListTbl.getValueAt(invoiceListTbl.getSelectedRow(), 1);
            if(r.payRetailer(ri.getInvoiceNumber(), Admin.payRetailer(ri))) {
                JOptionPane.showMessageDialog(null, "Amount paid to "+r.getRetailerName());
                populateInvoiceTbl();
            } else {
                JOptionPane.showMessageDialog(null, "Payment Failed");
            }
        } else {
            JOptionPane.showMessageDialog(null, "Please select a row");
        }
    }//GEN-LAST:event_payBtnActionPerformed

    private void backBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backBtnActionPerformed
        cards.remove(this);
        CardLayout cLayout = (CardLayout) cards.getLayout();
        cLayout.previous(cards);
    }//GEN-LAST:event_backBtnActionPerformed

    private void formComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_formComponentShown
        updateTresury();
    }//GEN-LAST:event_formComponentShown


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel amountLbl;
    private javax.swing.JButton backBtn;
    private javax.swing.JLabel headingAdmin;
    private javax.swing.JTable invoiceListTbl;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton payBtn;
    private javax.swing.JLabel treasuryLbl;
    // End of variables declaration//GEN-END:variables
}
